"""B2C SaaS raw source tables.

``RAW_TABLES`` order is the loading-model iteration order — it feeds RNG draw
order, so reordering changes generated bytes. Append only.
"""

from __future__ import annotations

from ...output.schemas import TableSpec
from ...shared.tables import AD_SPEND, SESSIONS

USERS = TableSpec(
    schema="app_db",
    name="users",
    pk="user_id",
    loading_ref="created_at",
    columns={
        "user_id": "BIGINT",
        "email": "VARCHAR",
        "full_name": "VARCHAR",
        "country": "VARCHAR",
        "signup_channel": "VARCHAR",
        "device_at_signup": "VARCHAR",
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

PLANS = TableSpec(
    schema="app_db",
    name="plans",
    pk="plan_id",
    reference_data=True,
    columns={
        "plan_id": "BIGINT",
        "name": "VARCHAR",
        "billing_period": "VARCHAR",
        "price": "DOUBLE",
        "currency": "VARCHAR",
        "_loaded_at": "TIMESTAMP",
    },
)

SUBSCRIPTIONS = TableSpec(
    schema="app_db",
    name="subscriptions",
    pk="subscription_id",
    loading_ref=("started_at", "trial_start_at"),  # coalesce paid start onto trial start
    columns={
        "subscription_id": "BIGINT",
        "user_id": "BIGINT",
        "plan_id": "BIGINT",
        "status": "VARCHAR",  # trialing | active | past_due | canceled
        "trial_start_at": "TIMESTAMP",
        "trial_end_at": "TIMESTAMP",
        "started_at": "TIMESTAMP",  # paid start (nullable)
        "canceled_at": "TIMESTAMP",  # nullable
        "_loaded_at": "TIMESTAMP",
    },
)

SUBSCRIPTION_EVENTS = TableSpec(
    schema="app_db",
    name="subscription_events",
    pk="event_id",
    event_time="occurred_at",
    columns={
        "event_id": "BIGINT",
        "subscription_id": "BIGINT",
        "user_id": "BIGINT",
        "event_type": "VARCHAR",
        "from_plan_id": "BIGINT",  # nullable
        "to_plan_id": "BIGINT",  # nullable
        "occurred_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

INVOICES = TableSpec(
    schema="billing",
    name="invoices",
    pk="invoice_id",
    event_time="issued_at",
    columns={
        "invoice_id": "BIGINT",
        "subscription_id": "BIGINT",
        "user_id": "BIGINT",
        "amount": "DOUBLE",
        "currency": "VARCHAR",
        "period_start": "DATE",
        "period_end": "DATE",
        "status": "VARCHAR",  # paid | open | void | uncollectible
        "issued_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

PAYMENTS = TableSpec(
    schema="billing",
    name="payments",
    pk="payment_id",
    event_time="created_at",
    columns={
        "payment_id": "BIGINT",
        "invoice_id": "BIGINT",
        "user_id": "BIGINT",
        "amount": "DOUBLE",
        "currency": "VARCHAR",
        "payment_method": "VARCHAR",
        "status": "VARCHAR",  # succeeded | failed
        "failure_code": "VARCHAR",  # nullable
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

PRODUCT_EVENTS = TableSpec(
    schema="product",
    name="events",
    pk="event_id",
    event_time="occurred_at",
    columns={
        "event_id": "BIGINT",
        "user_id": "BIGINT",
        "event_name": "VARCHAR",
        "plan_at_event": "VARCHAR",
        "country": "VARCHAR",
        "device": "VARCHAR",
        "occurred_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

RAW_TABLES: list[TableSpec] = [
    AD_SPEND,
    SESSIONS,
    USERS,
    PLANS,
    SUBSCRIPTIONS,
    SUBSCRIPTION_EVENTS,
    INVOICES,
    PAYMENTS,
    PRODUCT_EVENTS,
]
