"""Vertical-split migration pin: B2C SaaS output stays byte-identical.

Compares freshly generated parquet exports against the hashes pinned in
tests/golden/b2c_hashes.json (written by scripts/golden_hashes.py).
meta.run_manifest is excluded there; see the script docstring.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fake_companies.config import load_config
from fake_companies.generate import run_generation
from fake_companies.output.export import export_hashes

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDEN = json.loads((Path(__file__).parent / "golden" / "b2c_hashes.json").read_text())


@pytest.mark.slow
@pytest.mark.parametrize("config_name", sorted(GOLDEN))
def test_output_matches_golden(config_name: str, tmp_path: Path) -> None:
    cfg = load_config(REPO_ROOT / "configs" / f"{config_name}.yaml")
    db = tmp_path / "out.duckdb"
    run_generation(cfg, db, sidecar_dir=tmp_path)
    hashes = export_hashes(db, tmp_path / "export")
    hashes.pop("meta.run_manifest.parquet", None)
    assert hashes == GOLDEN[config_name], (
        f"{config_name}: parquet output drifted from the golden pin — "
        "a migration PR must not change generated bytes"
    )
