"""Retail DTC raw source tables.

``RAW_TABLES`` order is the loading-model iteration order — it feeds RNG draw
order, so reordering changes generated bytes. Append only.
"""

from __future__ import annotations

from ...output.schemas import TableSpec
from ...shared.tables import AD_SPEND, SESSIONS

PRODUCTS = TableSpec(
    schema="shop_db",
    name="products",
    pk="sku_id",
    reference_data=True,
    columns={
        "sku_id": "BIGINT",
        "sku": "VARCHAR",
        "product_name": "VARCHAR",
        "category": "VARCHAR",
        "color": "VARCHAR",
        "size": "VARCHAR",
        "price": "DOUBLE",
        "unit_cost": "DOUBLE",
        "currency": "VARCHAR",
        "_loaded_at": "TIMESTAMP",
    },
)

CUSTOMERS = TableSpec(
    schema="shop_db",
    name="customers",
    pk="customer_id",
    loading_ref="created_at",
    columns={
        "customer_id": "BIGINT",
        "email": "VARCHAR",
        "full_name": "VARCHAR",
        "country": "VARCHAR",
        "first_channel": "VARCHAR",
        "first_device": "VARCHAR",
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

ORDERS = TableSpec(
    schema="shop_db",
    name="orders",
    pk="order_id",
    event_time="placed_at",
    columns={
        "order_id": "BIGINT",
        "customer_id": "BIGINT",
        "session_id": "BIGINT",  # nullable: repeat orders carry no session
        "channel": "VARCHAR",
        "country": "VARCHAR",
        "device": "VARCHAR",
        "is_first_order": "BOOLEAN",
        "discount_code": "VARCHAR",  # nullable
        "item_count": "INTEGER",  # units across all lines
        "gross_amount": "DOUBLE",  # merchandise subtotal
        "discount_amount": "DOUBLE",
        "shipping_amount": "DOUBLE",
        "total_amount": "DOUBLE",  # gross - discount + shipping
        "currency": "VARCHAR",
        "placed_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

ORDER_ITEMS = TableSpec(
    schema="shop_db",
    name="order_items",
    pk="order_item_id",
    event_time="placed_at",
    columns={
        "order_item_id": "BIGINT",
        "order_id": "BIGINT",
        "sku_id": "BIGINT",
        "category": "VARCHAR",
        "quantity": "INTEGER",
        "unit_price": "DOUBLE",
        "line_amount": "DOUBLE",  # quantity * unit_price
        "placed_at": "TIMESTAMP",  # denormalized order event time
        "_loaded_at": "TIMESTAMP",
    },
)

SHIPMENTS = TableSpec(
    schema="fulfillment",
    name="shipments",
    pk="shipment_id",
    event_time="placed_at",  # loading anchors on order placement, not (nullable) shipping
    columns={
        "shipment_id": "BIGINT",
        "order_id": "BIGINT",
        "carrier": "VARCHAR",
        "status": "VARCHAR",  # pending | shipped | delivered
        "placed_at": "TIMESTAMP",
        "shipped_at": "TIMESTAMP",  # nullable (right-censored)
        "delivered_at": "TIMESTAMP",  # nullable (right-censored)
        "_loaded_at": "TIMESTAMP",
    },
)

RETURNS = TableSpec(
    schema="shop_db",
    name="returns",
    pk="return_id",
    event_time="requested_at",
    columns={
        "return_id": "BIGINT",
        "order_id": "BIGINT",
        "order_item_id": "BIGINT",
        "sku_id": "BIGINT",
        "category": "VARCHAR",
        "quantity": "INTEGER",
        "reason": "VARCHAR",  # fit | changed_mind | damaged | quality
        "refund_amount": "DOUBLE",
        "requested_at": "TIMESTAMP",
        "refunded_at": "TIMESTAMP",  # nullable (refund still processing at cutoff)
        "_loaded_at": "TIMESTAMP",
    },
)

TRANSACTIONS = TableSpec(
    schema="payments",
    name="transactions",
    pk="payment_id",
    event_time="created_at",
    columns={
        "payment_id": "BIGINT",
        "order_id": "BIGINT",
        "kind": "VARCHAR",  # charge | refund
        "amount": "DOUBLE",
        "currency": "VARCHAR",
        "payment_method": "VARCHAR",
        "status": "VARCHAR",  # succeeded | failed
        "failure_code": "VARCHAR",  # nullable
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

RAW_TABLES: list[TableSpec] = [
    AD_SPEND,  # shared spec: ad_platform.ad_spend
    SESSIONS,  # shared spec: web.sessions
    PRODUCTS,
    CUSTOMERS,
    ORDERS,
    ORDER_ITEMS,
    SHIPMENTS,
    RETURNS,
    TRANSACTIONS,
]
