"""B2B services raw source tables.

``RAW_TABLES`` order is the loading-model iteration order — it feeds RNG draw
order, so reordering changes generated bytes. Append only.

Note there is deliberately no ad_platform/web layer: the sales-led model has
no site traffic. The billing schema reuses the fqn ``billing.invoices`` /
``billing.payments`` with B2B-shaped columns — table specs are vertical-owned,
and only one vertical writes a given database.
"""

from __future__ import annotations

from ...output.schemas import TableSpec

ACCOUNTS = TableSpec(
    schema="crm",
    name="accounts",
    pk="account_id",
    loading_ref="created_at",
    columns={
        "account_id": "BIGINT",
        "name": "VARCHAR",
        "industry": "VARCHAR",
        "size_tier": "VARCHAR",  # smb | mid_market | enterprise
        "region": "VARCHAR",
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

CONTACTS = TableSpec(
    schema="crm",
    name="contacts",
    pk="contact_id",
    loading_ref="created_at",
    columns={
        "contact_id": "BIGINT",
        "account_id": "BIGINT",
        "full_name": "VARCHAR",
        "email": "VARCHAR",
        "title": "VARCHAR",
        "created_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

DEALS = TableSpec(
    schema="crm",
    name="deals",
    pk="deal_id",
    loading_ref="created_at",
    columns={
        "deal_id": "BIGINT",
        "account_id": "BIGINT",
        "contact_id": "BIGINT",
        "source": "VARCHAR",
        "industry": "VARCHAR",  # denormalized from the account for slicing
        "size_tier": "VARCHAR",
        "region": "VARCHAR",
        "stage": "VARCHAR",  # current pipeline stage | closed_won | closed_lost
        "amount": "DOUBLE",  # deal value estimate (booked value when won)
        "currency": "VARCHAR",
        "created_at": "TIMESTAMP",
        "closed_at": "TIMESTAMP",  # nullable: open deals
        "_loaded_at": "TIMESTAMP",
    },
)

DEAL_STAGE_EVENTS = TableSpec(
    schema="crm",
    name="deal_stage_events",
    pk="event_id",
    event_time="occurred_at",
    columns={
        "event_id": "BIGINT",
        "deal_id": "BIGINT",
        "account_id": "BIGINT",
        "stage": "VARCHAR",  # stage entered (incl. closed_won / closed_lost)
        "occurred_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

CONTRACTS = TableSpec(
    schema="billing",
    name="contracts",
    pk="contract_id",
    loading_ref="signed_at",
    columns={
        "contract_id": "BIGINT",
        "deal_id": "BIGINT",
        "account_id": "BIGINT",
        "value": "DOUBLE",
        "currency": "VARCHAR",
        "signed_at": "TIMESTAMP",
        "delivery_at": "TIMESTAMP",  # nullable: not yet delivered at cutoff
        "_loaded_at": "TIMESTAMP",
    },
)

INVOICES = TableSpec(
    schema="billing",
    name="invoices",
    pk="invoice_id",
    event_time="issued_at",
    columns={
        "invoice_id": "BIGINT",
        "contract_id": "BIGINT",
        "account_id": "BIGINT",
        "kind": "VARCHAR",  # upfront | balance
        "amount": "DOUBLE",
        "currency": "VARCHAR",
        "status": "VARCHAR",  # paid | open
        "issued_at": "TIMESTAMP",
        "due_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

PAYMENTS = TableSpec(
    schema="billing",
    name="payments",
    pk="payment_id",
    event_time="paid_at",
    columns={
        "payment_id": "BIGINT",
        "invoice_id": "BIGINT",
        "account_id": "BIGINT",
        "amount": "DOUBLE",
        "currency": "VARCHAR",
        "method": "VARCHAR",  # ach | wire | check
        "paid_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

RAW_TABLES: list[TableSpec] = [
    ACCOUNTS,
    CONTACTS,
    DEALS,
    DEAL_STAGE_EVENTS,
    CONTRACTS,
    INVOICES,
    PAYMENTS,
]
