"""CPG wholesale raw source tables.

``RAW_TABLES`` order is the loading-model iteration order — it feeds RNG draw
order, so reordering changes generated bytes. Append only.

``pos.scan_sales`` is weekly-grain retailer scan data (one row per week x
banner x product) and loads on the ``weekly`` cadence.
"""

from __future__ import annotations

from ...output.schemas import TableSpec
from ...shared.tables import AD_SPEND

ACCOUNTS = TableSpec(
    schema="erp",
    name="accounts",
    pk="account_id",
    reference_data=True,  # trading partners predate the timeline
    columns={
        "account_id": "BIGINT",
        "name": "VARCHAR",
        "kind": "VARCHAR",  # retailer | distributor
        "channel_type": "VARCHAR",  # grocery | natural | mass | online | independents
        "banner": "VARCHAR",  # retailer banner served (distributors: independents)
        "region": "VARCHAR",
        "_loaded_at": "TIMESTAMP",
    },
)

PRODUCTS = TableSpec(
    schema="erp",
    name="products",
    pk="product_id",
    reference_data=True,
    columns={
        "product_id": "BIGINT",
        "sku": "VARCHAR",
        "product_name": "VARCHAR",
        "category": "VARCHAR",
        "case_size": "INTEGER",  # consumer units per case
        "case_price": "DOUBLE",  # wholesale price per case
        "msrp": "DOUBLE",  # suggested retail per consumer unit
        "currency": "VARCHAR",
        "_loaded_at": "TIMESTAMP",
    },
)

SHIPMENTS = TableSpec(
    schema="erp",
    name="shipments",
    pk="shipment_id",
    event_time="shipped_at",
    columns={
        "shipment_id": "BIGINT",
        "account_id": "BIGINT",
        "product_id": "BIGINT",
        "category": "VARCHAR",  # denormalized for slicing
        "channel_type": "VARCHAR",
        "cases": "INTEGER",
        "case_price": "DOUBLE",
        "gross_amount": "DOUBLE",
        "discount_amount": "DOUBLE",  # off-invoice trade discount
        "net_amount": "DOUBLE",
        "currency": "VARCHAR",
        "shipped_at": "TIMESTAMP",
        "_loaded_at": "TIMESTAMP",
    },
)

SCAN_SALES = TableSpec(
    schema="pos",
    name="scan_sales",
    pk="scan_id",
    event_time="week_start",
    loading_ref="week_start",  # DATE -> midnight; weekly feed
    columns={
        "scan_id": "BIGINT",
        "week_start": "DATE",
        "retailer_banner": "VARCHAR",
        "channel_type": "VARCHAR",
        "product_id": "BIGINT",
        "category": "VARCHAR",
        "units": "BIGINT",
        "dollars": "DOUBLE",
        "currency": "VARCHAR",
        "_loaded_at": "TIMESTAMP",
    },
)

TRADE_PROMOTIONS = TableSpec(
    schema="promo",
    name="trade_promotions",
    pk="promo_id",
    reference_data=True,  # planned in the trade calendar ahead of time
    columns={
        "promo_id": "BIGINT",
        "name": "VARCHAR",
        "retailer_banner": "VARCHAR",
        "category": "VARCHAR",
        "start_date": "DATE",
        "end_date": "DATE",
        "discount_pct": "DOUBLE",
        "_loaded_at": "TIMESTAMP",
    },
)

RAW_TABLES: list[TableSpec] = [
    AD_SPEND,  # shared spec: ad_platform.ad_spend (causally decoupled)
    ACCOUNTS,
    PRODUCTS,
    SHIPMENTS,
    SCAN_SALES,
    TRADE_PROMOTIONS,
]
